### ISSUE TITLE
MsdfGenerator issue on AWS CodeBuild CI/CD platform

### ISSUE THREAD

**Issue by tuncayyildirtanuk** [lightning-js/blits#125]
When configuring Vite via blitsVitePlugins, I encountered the following issue exclusively on the AWS CodeBuild platform.

![Screenshot 2024-07-25 at 13 42 14](https://github.com/user-attachments/assets/5529c24e-1f7c-4963-b9ea-dde0822f5ce8)

As a workaround, I used only the preCompiler and temporarily removed the msdfGenerator.

```
import { defineConfig } from 'vite';
import blitsVitePlugins from '@lightningjs/blits/vite';

// Get the preCompiler plugin
// msdfGenerator not working as expected. Raised an issue on the Blits repo
const preCompilerPlugin = blitsVitePlugins.find((item) => item.name === 'preCompiler');

/* eslint-disable no-unused-vars */
export default defineConfig(({ command, mode, ssrBuild }) => {
  return {
    base: '/', // Set to your base path if you are deploying to a subdirectory (example: /myApp/)
    plugins: [preCompilerPlugin],
    resolve: {
      mainFields: ['browser', 'module', 'jsnext:main', 'jsnext'],
    },
   ....
  };
});

```

Should we include msdfGenerator when building a Blits app?

**Comment by michielvandergeest** [comment]
@tuncayyildirtanuk Thanks for this report. From what I can tell, this error seems to be generated by the [msdf-generator](https://github.com/lightning-js/msdf-generator) package and not per se by Blits. Obviously the Blits provided vite plugin is your gateway into this package, so it's still a valid issue to be aware of from the Blits perspective.

As an immediate solution / workaround, you could place the generated msdf font files (png and json) into your publics/fonts folder and reference those in the launch settings. That way the msdf generation step is skipped all together.

As for the error itself, it seems like a similar one that's been reported here: https://github.com/lightning-js/msdf-generator/issues/5
That one may be related to the node version used (16 whereas, 18 is marked as minimum). Could you verify the node version used in AWS CodeBuild platform?

**Comment by tuncayyildirtanuk** [comment]
Yes it is same issue like https://github.com/lightning-js/msdf-generator/issues/5

Node version is 18.19.0

![Screenshot 2024-07-25 at 14 58 03](https://github.com/user-attachments/assets/bdfb0bee-6502-41a8-b03b-3c14e5c90b32)

Also I guess minimum node version might be `20.9.0` for the `renderer` perspective?

**Comment by tuncayyildirtanuk** [comment]
I have updated and tried after the following change. Same issue. 

<img width="957" alt="Screenshot 2024-07-25 at 15 25 04" src="https://github.com/user-attachments/assets/977546ac-36ba-41b2-bf70-44cdc71b6214">

**Comment by michielvandergeest** [comment]
You should be able to leave your font launch setting the same, just placing the generated json and png file in the correct location alongside your ttf should be enough.

Alternatively you can specify the location to the json file and the png file explicitly, like this:

```
{
      family: 'lato',
      type: 'msdf',
      png: 'fonts/lato.png',
      json: 'fonts/lato.json',
},
```

**Comment by tuncayyildirtanuk** [comment]
I have attempted the following scenarios, but the issue persists:

1. Copied the OpenSans-Medium.msdf.json and OpenSans-Medium.msdf.png files to the public/fonts folder.
2. Updated the launch configuration as follows:

<img width="804" alt="Screenshot 2024-07-26 at 10 29 12" src="https://github.com/user-attachments/assets/1fb3856c-9cfe-4e79-8d6e-31754ad1417f">

**Comment by tuncayyildirtanuk** [comment]
Hi, I just tested via blits version 1.0.2. 

I would like to share results.

# CI/CD Result:

<img width="1505" alt="Screenshot 2024-08-05 at 12 34 37" src="https://github.com/user-attachments/assets/33f71198-12b1-458b-9ce8-c67a548ad859">

# Public font files
<img width="1197" alt="Screenshot 2024-08-05 at 12 35 30" src="https://github.com/user-attachments/assets/5879a5a5-41df-4e20-ba4c-f39b3a95c221">

# Font files configuration.
<img width="680" alt="Screenshot 2024-08-05 at 12 35 47" src="https://github.com/user-attachments/assets/ef521ff2-0437-45dc-9b7d-7337074701a5">

**Comment by michielvandergeest** [comment]
Ah, I don't think you can have 2 families with the same name in your fonts config. If you rename the msdf font to a different family name, it should work I think.

**Comment by michielvandergeest** [comment]
As for the font generation error, it seems like this is related to the nodeJS version (https://github.com/lightning-js/msdf-generator/issues/5#issuecomment-2262673440)
