### ISSUE TITLE
RTT

### ISSUE THREAD

**Issue by QuintinKrugerMC** [lightning-js/blits#189]
I’ve been building an app and tried using rtt flag to optimize some animations in my app. When I use rtt=”true” - the elements just seem to disappear? I’ve tried in the example app putting rtt="true" on PortalItem and get

![image](https://github.com/user-attachments/assets/16565ae7-e380-40f0-a67d-2c5fd4ed273e)

**Comment by michielvandergeest** [comment]
Hi Quintin, did you add dimensions to the Element with the `rtt`-attribute? The holder Element needs a predefined width and height in order to be able to render to a texture.
