### ISSUE TITLE
Rename ‘function’ key in transition object to ‘easing’

### ISSUE THREAD

**Issue by michielvandergeest** [lightning-js/blits#76]
Currently the transition object can have a ‘function’ key to specify a custom timing function. In retrospect this name isn’t as descriptive as I wanted it to be. Also, using the key ‘function’ in the template can throw off the code highlighting in the VS code plugin.

In order to address these 2 issues, we should  rename the key ‘function’  to ‘easing’

Before: 

```js
<Element :y.transition=“{v: $y, function: ‘ease-in-out’}” />
```

After:
 
```js
<Element :y.transition=“{v: $y, easing: ‘ease-in-out’}” />
```

This will be a breaking change. As we are in beta, I don’t think we need to follow a full deprecation path. But we should log a descriptive error when the old ‘function’ key is used in a transition object, to make it straightforward to make the necessary fixes in the app code.

**Comment by sandeep-vedam** [comment]
This issue is addressed with #78 . Hence closing this.
