### ISSUE TITLE
Blits.Launch: Handle empty settings

### ISSUE THREAD

**Issue by EwanRoycroft** [lightning-js/blits#93]
I was just getting started with Blits and was confused to get errors like "Cannot use 'in' operator to search for 'fontLoader' in undefined" and "Cannot read properties of undefined (reading 'w')". Turns out I hadn't provided any settings object to `Blits.Launch()`. 

I suggest either handling an undefined/null settings object, or throwing a more meaningful error if one is provided.

**Comment by michielvandergeest** [comment]
Released in 0.9.9.
