### ISSUE TITLE
window.parent overwritten when using :for directive

### ISSUE THREAD

**Issue by WoodingMP** [lightning-js/blits#94]
When writing Blits components, if you use `:for` to generate elements from an array, window.parent will be overwritten with a Blits component, when it should be a reference to itself or its actual parent - see ([`window.parent`](https://developer.mozilla.org/en-US/docs/Web/API/Window/parent)). 

### Reproducability
The issue can be found on any page that uses a `:for` loop. To reproduce the issue:

1. Go to the [blits demo](https://blits-demo.lightningjs.io/#/) and open developer tools
2. Go to the sources tab and add a watcher to `window.parent`
3. Reload the page, and after it's loaded, refresh the watcher
4. Notice that `window.parent` is set to a Blits component

<img width="1531" alt="image" src="https://github.com/lightning-js/blits/assets/44930483/345b7a06-1af0-4287-adef-0a93c7ada17f">

5. Visit any page that doesn't use a `:for` loop (e.g. [intro](https://blits-demo.lightningjs.io/#/demos/intro))
6. Refresh the watcher and notice that `window.parent` is correctly set to a reference of `window`

<img width="1531" alt="image" src="https://github.com/lightning-js/blits/assets/44930483/34594d2b-bfd8-42c2-b131-f1a828064b20">

### Playground
I've also setup a playground to show specifically that it is the :for property that is causing this. Open both playgrounds and view the console, in the ready hook, the window and window.parent will be logged and you'll notice in the playground with the for loop, window.parent is logged as a Blits component.
[Playground without for](https://playground.lightningjs.io/#N4IgZgTghgtgpgdwPYQNYgFwgEYBsCWALgM4gA04+ucpGA2qAHaxyYgCCADpwHQBWpCsSQBXCAGNWWfDE4pCAAgBCBEgshIYCgOQABAgHMAFoUb5GBgQHo8RYtoA6jJ3AAeciIoAmcMFBG4iip2PFycBOJQhPhIjAAUwE4KyQrEhFFwcQCUComMKQUKEHCEYvl5hZUKRHAwxBgKdACMZABMZADMALpJVQC+vcl9ZIMKhLXhGQ0ABqMFADwAotTwjIQAfHNV8wAqboriseNrALwOIMFq+MQKUAg0mnDn6-NWe64bW5VLK3BrCggziAAKwABnOCiMQLBEMOuBQQIAxGBQeCQAoAJ7QtEKDCuIEANhxVk2+W2VmWtT+nzJyWmI1pkKQSFQ9VyXyKcCgXgx2XZjKqCkOjGE1B48IMcQQ5i8SAQZABMrlPE4UGKayyAG4OQNGbq+lqQH0uhQfJw-j5GOJ8DRMAwQMx4Gx9PhjKZzJZiDZVIIQGJcGwTIROPUrFYaDAeMQjFYXW6zBZrLYSEaun0gA)
<img width="1728" alt="image" src="https://github.com/lightning-js/blits/assets/44930483/50e1d53f-4edc-430d-a8b0-828e61fa9f1b">

[Playground with for](https://playground.lightningjs.io/#N4IgZgTghgtgpgdwPYQNYgFwgEYBsCWALgM4gA04+ucpGA2qAHaxyYgCCADpwHQBWpCsSQBXCAGNWWfDE4pCAAgBCBEgshIYCgOQABAgHMAFoUb5GBgQHo8RYtoA6jJ3AAeciIoAmcMFBG4iip2PFycBOJQhPhIjAAUwE4KyQrEhFFwcQCUComMKQUKEHCEYvl5hZUKRHAwxBgKdACMZABMZADMALpJVQC+vcl9ZIMKhLXhGQ0ABqMFADwAotTwjIQAfHNV8wAqboriseNrALwOIMFq+MQKUAg0mnDn6-NWe64bW5VLK3BrChgwCgziA4jUYGRqowfK4cuYFAAScHEc4KBAggCsAAZUUZMTiQApDrhgecAMRgLEEhQAT3xqIwrhBSOhbgUACoFAA2alWTb5bZWZa1P6fAXJaYjcUKIxIJCoeq5L5FOBQLw07JK6VVImxYTUHgkgxxBDmLxIBCQ03Qi08ThQYprLIAbmVA2l7r6LpAfS6FB8nD+PkY4nwNEwDBAzHgbH0+GMpnMlmINlUghAYlwbBMhE49SsVhoMB4xCMVjjCbMFmsthIPq6fSAA)
<img width="1728" alt="image" src="https://github.com/lightning-js/blits/assets/44930483/384d3fb1-747e-45ac-bae5-b9864629d883">

While this doesn't seem to cause any issues in the demo app, anywhere window.parent is relied upon will fail due to the incorrect object being set (I'm having issues with Storybook as it relies on it to capture frames).

**Comment by michielvandergeest** [comment]
hey @WoodingMP, I see the problem indeed. That's a very good find!!  

Luckily it also seems like a rather straight forward fix 🙂 Will look into this shortly.

Thanks for hunting and reporting this 👍

**Comment by michielvandergeest** [comment]
Should be fixed in #95.

Appreciated if you could verify this on your end as well. Thanks again 🙂

**Comment by WoodingMP** [comment]
@michielvandergeest works great now thanks for getting on it so fast!
