### ISSUE TITLE
Typescript errors when referencing methods/props/state using this (0.9.9)

### ISSUE THREAD

**Issue by WoodingMP** [lightning-js/blits#96]
After updating to the latest 0.9.9 release, I've found that I get typescript errors all over my components now where I'm using `this.` when in reference to a method, property, or state value. Now the only known properties on this are the methods inside `computed`

Is there a new way I should be referencing everything with the latest updates to type definitions?
e.g.
`...
props: ['test'],
computed: {
getTest(): string {
 return this.test
}
}
...
`
gives the error 
> Property 'test' does not exist on type '{ getTest(): string; }'.ts(2339)

**Comment by michielvandergeest** [comment]
Closing as this should be fixed with the latest TS refactor.
