### ISSUE TITLE
Array of objects reactivity isn't working

### ISSUE THREAD

**Issue by flexiapp** [lightning-js/blits#98]
I have array of objects, e.g. let x = [{"id":1,"name":"aaa"},{"id":2,"name":"bbb"}]; and use this array in for loop.
When i update object value, reactivity isn't working.

**Comment by michielvandergeest** [comment]
Hi @flexiapp, thanks for your report. You are correct, this has been a known issue in the reactivity of arrays.

We've recently addressed this issue, as part of a bigger refactor on the `feature/codegenerator-improvements` branch. This branch addresses some other issues as well and contains a number of performance improvements. There are a few loose ends on that branch that we hope to tie up this week, before we merge it into master and released

**Comment by michielvandergeest** [comment]
This is now working as you would expect on master (v.1.0.0)
